{{- if and (gt (int .Values.query_frontend.replicas) 1) (.Values.query_frontend.podDisruptionBudget) }}
apiVersion: {{ include "cortex.pdbVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "cortex-query-frontend.fullname" . }}
  labels: {{ include "cortex-query-frontend.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "cortex-query-frontend.matchLabels" . | nindent 6 }}
{{ toYaml .Values.query_frontend.podDisruptionBudget | indent 2 }}
{{- end }}
