{{- if and (gt (int .Values.store_gateway.replicas) 1) (.Values.store_gateway.podDisruptionBudget) }}
apiVersion: {{ include "cortex.pdbVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "cortex-store-gateway.fullname" . }}
  labels: {{ include "cortex-store-gateway.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "cortex-store-gateway.matchLabels" . | nindent 6 }}
{{ toYaml .Values.store_gateway.podDisruptionBudget | indent 2 }}
{{- end }}
