{{- if eq .Values.config.storage.engine "blocks" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cortex-store-gateway.headlessname" . }}
  labels: {{ include "cortex-store-gateway.labels" . | nindent 4 }}
{{- with .Values.store_gateway.labels }}
{{- toYaml . | indent 4 }}
{{- end }}
  annotations:
    {{- toYaml .Values.store_gateway.annotations | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
    - port: {{ .Values.config.server.grpc_listen_port }}
      protocol: TCP
      name: grpclb
      targetPort: grpc      
  selector: {{ include "cortex-store-gateway.matchLabels" . | nindent 4 }}
{{- end -}}
