{{- if .Values.ruler.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "cortex-ruler.fullname" . }}
  labels: {{ include "cortex-ruler.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "cortex-ruler.matchLabels" . | nindent 6 }}
{{ toYaml .Values.ruler.podDisruptionBudget | indent 2 }}
{{- end -}}
