{{- if .Values.ruler.enabled }}
{{- range $dir, $files := .Values.ruler.directories }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cortex-ruler.fullname" $ }}-{{ include "cortex-ruler.dirName" $dir }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "cortex-ruler.labels" $ | nindent 4 }}
data:
  {{- toYaml $files | nindent 2}}
{{- end }}
{{- end }}
