{{- if ne .Values.config.storage.engine "blocks" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cortex-table-manager.fullname" . }}
  labels: {{ include "cortex-table-manager.labels" . | nindent 4 }}
{{- with .Values.table_manager.labels }}
{{- toYaml . | indent 4 }}
{{- end }}
  annotations:
    {{- toYaml .Values.table_manager.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector: {{ include "cortex-table-manager.matchLabels" . | nindent 4 }}
{{- end -}}
