{{- if not .Values.alertmanager.statefulSet.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cortex-alertmanager.fullname" . }}
  labels: {{ include "cortex-alertmanager.labels" . | nindent 4 }}
    {{- with .Values.alertmanager.service.labels }}
{{- toYaml . | indent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.alertmanager.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector: {{ include "cortex-alertmanager.matchLabels" . | nindent 4 }}
{{- end }}
