{{- if and (gt (int .Values.alertmanager.replicas) 1) (.Values.alertmanager.podDisruptionBudget) }}
apiVersion: {{ include "cortex.pdbVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "cortex-alertmanager.fullname" . }}
  labels: {{ include "cortex-alertmanager.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "cortex-alertmanager.matchLabels" . | nindent 6 }}
{{ toYaml .Values.alertmanager.podDisruptionBudget | indent 2 }}
{{- end }}
