apiVersion: v1
kind: Service
metadata:
  name: {{ template "cortex-querier.fullname" . }}
  labels: {{ include "cortex-querier.labels" . | nindent 4 }}
{{- with .Values.querier.labels }}
{{- toYaml . | indent 4 }}
{{- end }}
  annotations:
    {{- toYaml .Values.querier.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector: {{ include "cortex-querier.matchLabels" . | nindent 4 }}
