{{- if and (gt (int .Values.querier.replicas) 1) (.Values.querier.podDisruptionBudget) }}
apiVersion: {{ include "cortex.pdbVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "cortex-querier.fullname" . }}
  labels: {{ include "cortex-querier.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "cortex-querier.matchLabels" . | nindent 6 }}
{{ toYaml .Values.querier.podDisruptionBudget | indent 2 }}
{{- end }}
