{{- if .Values.alertmanager.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortex.alertmanagerFullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cortex.alertmanagerLabels" . | nindent 4 }}
    {{- with .Values.alertmanager.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.alertmanager.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
    - port: {{ .Values.config.server.grpc_listen_port }}
      protocol: TCP
      name: grpc
      targetPort: grpc
    - port: 9094
      protocol: UDP
      name: alert-clu-udp
      targetPort: alert-clu-udp
    - port: 9094
      protocol: TCP
      name: alert-clu-tcp
      targetPort: alert-clu-tcp
  selector:
    {{- include "cortex.alertmanagerSelectorLabels" . | nindent 4 }}
{{- end -}}
