{{- if .Values.alertmanager.enabled -}}
{{- if .Values.alertmanager.statefulSet.enabled -}}
{{- $clusterPort := regexReplaceAll ".+[:]" .Values.config.alertmanager.cluster.listen_address "" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortex.alertmanagerFullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cortex.alertmanagerLabels" . | nindent 4 }}
    {{- with .Values.alertmanager.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.alertmanager.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ $clusterPort }}
      protocol: TCP
      name: cluster-tcp
      targetPort: cluster-tcp
    - port: {{ $clusterPort }}
      protocol: UDP
      name: cluster-udp
      targetPort: cluster-udp
  selector:
    {{- include "cortex.alertmanagerSelectorLabels" . | nindent 4 }}
{{- end -}}
{{- end -}}
