{{- if and (gt (int .Values.ingester.replicas) 1) (.Values.ingester.podDisruptionBudget) }}
{{- if or (.Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget") (semverCompare ">=1.21" .Capabilities.KubeVersion.Version) }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "cortex.ingesterFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cortex.ingesterLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cortex.ingesterSelectorLabels" . | nindent 6 }}
  {{- toYaml .Values.ingester.podDisruptionBudget | nindent 2 }}
{{- end }}
