{{- if and .Values.compactor.enabled (eq .Values.config.storage.engine "blocks") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cortex-compactor.headlessname" . }}
  labels: {{ include "cortex-compactor.labels" . | nindent 4 }}
    {{- with .Values.compactor.service.labels }}
{{- toYaml . | indent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.compactor.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector: {{ include "cortex-compactor.matchLabels" . | nindent 4 }}
{{- end }}
