{{- if .Values.distributor.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "cortex-distributor.fullname" . }}
  labels: {{ include "cortex-distributor.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "cortex-distributor.matchLabels" . | nindent 6 }}
{{ toYaml .Values.distributor.podDisruptionBudget | indent 2 }}
{{- end -}}
