{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cortex-nginx.fullname" . }}
  labels: {{ include "cortex-nginx.labels" . | nindent 4 }}
{{- with .Values.nginx.labels }}
{{- toYaml . | indent 4 }}
{{- end }}
  annotations:
    {{- toYaml .Values.nginx.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.nginx.http_listen_port }}
      protocol: TCP
      name: http
      targetPort: http
  selector: {{ include "cortex-nginx.matchLabels" . | nindent 4 }}
{{- end }}
