{{- if and (gt (int .Values.ingester.replicas) 1) (.Values.ingester.podDisruptionBudget) }}
apiVersion: {{ include "cortex.pdbVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "cortex-ingester.fullname" . }}
  labels: {{ include "cortex-ingester.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "cortex-ingester.matchLabels" . | nindent 6 }}
{{ toYaml .Values.ingester.podDisruptionBudget | indent 2 }}
{{- end }}
