---
{{- if .Values.dynamodbLocal.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-dynamodb
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 8000
  selector:
    app: {{ template "name" . }}-dynamodb
    release: {{ .Release.Name }}
{{- end }}
