{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "cortex.fullname" . }}
  labels:
    {{- include "cortex.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cortex.selectorLabels" . | nindent 4 }}
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
{{- end -}}
