{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "cortex.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "cortex.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ template "cortex.name" . }}
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
{{- end -}}
