{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{ include "cortex.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  name: {{ template "cortex.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}

