{{- if and (gt (int .Values.compactor.replicas) 1) (.Values.compactor.podDisruptionBudget) }}
apiVersion: {{ include "cortex.pdbVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "cortex-compactor.fullname" . }}
  labels: {{ include "cortex-compactor.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "cortex-compactor.matchLabels" . | nindent 6 }}
{{ toYaml .Values.compactor.podDisruptionBudget | indent 2 }}
{{- end }}
