{{- if and (gt (int .Values.distributor.replicas) 1) (.Values.distributor.podDisruptionBudget) }}
{{- if or (.Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget") (semverCompare ">=1.21" .Capabilities.KubeVersion.Version) }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "cortex.distributorFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cortex.distributorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cortex.distributorSelectorLabels" . | nindent 6 }}
  {{- toYaml .Values.distributor.podDisruptionBudget | nindent 2 }}
{{- end }}
