apiVersion: v1
kind: Service
metadata:
  name: {{ template "cortex-distributor.fullname" . }}
  labels: {{ include "cortex-distributor.labels" . | nindent 4 }}
    {{- with .Values.distributor.labels }}
{{- toYaml . | indent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.distributor.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector: {{ include "cortex-distributor.matchLabels" . | nindent 4 }}
