name: Generate README.md

on:
  push:
    branches-ignore:
      - main
      - master
    paths:
      - values.yaml

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate README.md
        run: |
          make README.md

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: README.md
          default_author: github_actions
          message: "[skip ci] generate README.md"
          signoff: true
